repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort --check
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: black
        name: black
        entry: black --check
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: docformatter
        name: docformatter
        entry: docformatter --check
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: bandit
        name: bandit
        entry: bandit -c pyproject.toml -q
        language: system
        types: [ python ]
        stages: [ pre-commit ]
