repos:
  - repo: local
    hooks:
      - id: ruff-formatter
        name: ruff-formatter
        entry: ruff format --check
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [ python ]
        stages: [ pre-commit ]

      - id: ruff-linter
        name: ruff-linter
        entry: ruff check
        language: system
        types: [ python ]
        stages: [ pre-commit ]
