[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "todo-cli"
version = "0.0.1"
dependencies = ["typer"]

[project.optional-dependencies]
dev = ["isort", "black", "docformatter"]

[tool.isort]
profile = "black"

[tool.black]
line-length = 88

[tool.docformatter]
in-place = true
recursive = true
black = true
blank = true
