"""Add active column to spaces table.

Revision ID: ca66626ab021
Revises: bc131e6a2114
Create Date: 2024-06-15 09:01:19.134024+00:00

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "ca66626ab021"
down_revision: Union[str, None] = "bc131e6a2114"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "spaces",
        sa.Column(
            "active", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False
        ),
    )
    # ### end Alembic commands ###

    op.execute("UPDATE spaces SET active = TRUE WHERE id = 1;")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spaces", "active")
    # ### end Alembic commands ###
