"""Add disabled_at column to spaces table.

Revision ID: aab35dba9fe9
Revises: 86e531eecd2b
Create Date: 2024-06-15 07:30:14.218248+00:00

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "aab35dba9fe9"
down_revision: Union[str, None] = "86e531eecd2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("spaces", sa.Column("disabled_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("spaces", "disabled_at")
    # ### end Alembic commands ###
